server:
  port: 8080
  servlet:
    context-path: /guonl

spring:
  ## quartz定时任务,采用数据库方式
  quartz:
  job-store-type: jdbc
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true
    proxy-target-class: true

  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost/guonl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true&useSSL=false
      username: root
      password: abc-123456
      #配置初始化大小/最小/最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

    #redis 配置
    #    redis:
    #      database: 0
    #      host: 127.0.0.1
    #      lettuce:
    #        pool:
    #          max-active: 8   #最大连接数据库连接数,设 0 为没有限制
    #          max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
    #          max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    #          min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
    #        shutdown-timeout: 100ms
    #      password: ''
    #      port: 6379

    thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      mode: LEGACYHTML5
      cache: false

    #设置上传文件的大小
    servlet:
      multipart:
        max-file-size: 10Mb
        max-request-size: 100Mb


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.guonl.model


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


